### PR TITLE
Intergrate NeoFS

### PR DESCRIPTION
**Pull request by evgeniiz321**
@vncoelho can you please take a look? 
to startup the whole thing, just run ./startNeoFS.sh. I didn't add it to runDetachedCompose-EcoNodes.sh, cause not sure how you want to use it - start separately or together with existing nodes. But anyway, after ./startNeoFS.sh you will have 3 docker containers, that are ready to be used. In the end of ./startNeoFS.sh I create a neofs container and upload some random object, just as an example that it works.

### CODE REVIEW

**Review by vncoelho — COMMENTED** [review]
Very happy to see this PR!
Thank you,

I am at ETH Devcon this week. Next week I will check everything and run. Just let me recover from the jet lag then...ahhah

**Comment by vncoelho** [comment]
image

As you described, everything is working.

Can you please send an example of a smart contract using NeoFS?

I will include it on the default compiling contracts. Please also send some functions to invoke it and test. I will guide everything to be replicated by those who use our system.

**Comment by roman-khimov** [comment]
Standard Oracle contracts work well for it, it's just that you use `neofs:` URIs as in https://github.com/neo-project/neo/issues/1256, like `neofs:6pJtLUnGqDxE2EitZYLsDzsfTDVegD6BrRUn8QAFZWyt/5Cyxb3wrHDw5pqY63hb5otCSsJ24ZfYmsA8NAjtho2gr`. But this obviously requires uploading an object first which can be done with neofs-cli.

**Comment by vncoelho** [comment]
@roman-khimov, can you provide some example that the SC upload such object?

**Comment by roman-khimov** [comment]
You can't upload from SC, that's the problem, see https://github.com/neo-project/neo/issues/1980.

**Comment by evgeniiz321** [comment]
In the end of a startup script - https://github.com/NeoResearch/neocompiler-eco/pull/109/files#diff-4b4d858bf4ee11e6a809f335804c22f51c649767485c75ca4e2959620b609b97R78
there are calls to create container and upload object:
```
docker exec neofs-storage-node /neofs-cli --config /wallets/multipurpose-wallet-config.yml object put --cid "$container_id" --file /wallets/multipurpose-wallet-config.yml --no-progress --timeout '60s' --rpc-endpoint "$NEOFS_STORAGE_NODE_RPC_ENDPOINT" --wallet /wallets/multipurpose-wallet.json
```
So, one object is uploaded by default, you can reuse it if needed. Or can create additional ones.

**Pull request merged**
