### PR TITLE
feat: improved UI and persist Wallet

### PR DESCRIPTION
**Pull request by ftgibran**
If you do not like this theme that I have implemented, I can easily change to another one or even rollback to the old one

### CODE REVIEW

**Comment by FabioRick** [comment]
Hello 😄 !
Do you have any light theme?
And also must fix the layout of the first row of the home page 😃 .

**Comment by ftgibran** [comment]
@FabioRick Yes, I do have
I will try another one and fix the layout of home page

**Comment by ftgibran** [comment]
@FabioRick Done

**Comment by igormcoelho** [comment]
Let's see this online :)

**Comment by FabioRick** [comment]
@ftgibran This one is really good 😃 !

**Comment by vncoelho** [comment]
That is true! Looks nice, thanks @ftgibran

**Pull request merged**
