### PR TITLE
UTXO and Claims from c# neo-cli instead of neoscan

### PR DESCRIPTION
**Pull request by vncoelho**
Preparing the code for UTXO migration to neo-cli

### CODE REVIEW

**Comment by vncoelho** [comment]
Thanks Jeff! https://github.com/neo-project/neo-plugins/pull/52 is a game changing

**Comment by jsolman** [comment]
@vncoelho Your welcome! :100:

**Comment by vncoelho** [comment]
Merging into master but still missing transfer and claims.
However, address status are now completely on neocli

**Comment by vncoelho** [comment]
Tagged as 3.0 before merge, since now we are going to clean many things.

**Pull request merged**
