### PR TITLE
Neo go compiler

### PR DESCRIPTION
**Pull request by stevenjack**
### Problem

There's no [neo-go](https://github.com/CityOfZion/neo-go) compiler support 😢.

### Solution

* Add `Dockerfile` for building `neo-go` binary to then allow compilation of `golang` contracts 😍.

Here's an example of a super simple :trollface: contract to test:

```go
package main

func Main() int {
	x := 10
	return x
}
```

### Notes

* In the future we'll have a pre-built container built on each tag of [neo-go](https://github.com/CityOfZion/neo-go),  however for the moment we'll manually build it.

### CODE REVIEW

**Comment by anthdm** [comment]
Pure awesomeness <3

**Comment by vncoelho** [comment]
thanks @steven and @anthony, it is surelt GOing to open paths for GO users to GO on Neo ecosystem. ;D

Here we go. Many thanks,

we gonna soon pull it locally here

**Comment by vncoelho** [comment]
Merged.

Thanks to both of you!! :dagger: 

I am trying to integrate the outputs of the compiler, but It did export directly.
The ABI should also work?
However, it seems that the avm was generated correctly, as expect.

@FabioRick and @igormcoelho, I will do a commit that, hopefully, will not make any problems to the csharp and python compilations, please, check it out! ahueaheuaea

**Comment by vncoelho** [comment]
The AVM of that simple example was 52c56b5a6c766b00527ac46203006c766b00c3616c7566

**Comment by anthdm** [comment]
Sweet!

**Pull request merged**
